/* February 8, 2023
Some practice problems for us to work on together!  Do NOT edit this file!
*/

/* Parens Valid (from Strings To Do 3):
Valid sets of parentheses always open before they close, for example. 
For "Y(3(p)p(3)r)s", return true. Given "N(0(p)3", return false: not every parenthesis is closed. 
Given "N(0)t )0(k", return false, because the underlined ")" is premature: there is nothing open for it to close.
*/



/* Integer to Roman Numerals:
Given a positive integer that is less than 4000, return a string containing that value in Roman numeral
representation. In this representation, I is 1, V is 5, X is 10, L = 50, C = 100, D = 500, and M = 1000.
Remember that 4 is IV, 349 is CCCIL and 444 is CDXLIV.
*/



/* Reverse an array in place:
Given a numerical array, reverse the order of values, in-place.  The reversed array should have the 
same length, with existing elements moved to other indices so that order of elements is reversed.  
Working 'in-place' means that you cannot use a second array – move values within the array that you 
are given.  Do not use built-in array functions such as splice().
*/



/* Zip It
Create a standalone function that accepts two arrays and combines their values sequentially into 
a new array, at alternating indices starting with first array. Extra values from either array should 
be included afterward. Given [1,2] and [10,20,30,40], return a new array containing [1,10,2,20,30,40].
*/